name: Release to Crates.io

on:
  push:
    branches:
    - main
    tags:
      - '^v[0-9]+.[0-9]+.[0-9]+'

jobs:
  cargo-publish:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cargo publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

